name: release

on:
  push:
    tags:
    - "v*"

jobs:
  release:
    uses: nzbgetcom/nzbget-extensions/.github/workflows/extension-release.yml@main
    with:
      release-file-list: lib/ ChangeLog.txt README.* main.py manifest.json
      release-file-name: videosort
      release-dir: VideoSort
